In [82]:
import numpy as np
import pymatgen.symmetry.analyzer as analyzer
from pymatgen.ext.matproj import MPRester
import pymatgen.core.lattice 

with MPRester("v5zOFTlhqtoyEiw1") as m:
    material_id = "mp-753260"
    # Structure for material id
    structure = m.get_structure_by_material_id(material_id)
    structure.to(filename="LaAgO2_computed.cif")#computes the computed version
    
    #0 define new structure to obtain a=b=c and alpha=beta=gamma ainsi que le symmetrized et le conventional car je ne sais pas 
    #lequel je vais utiliser
    new_structure =  analyzer.SpacegroupAnalyzer(structure).get_primitive_standard_structure()
    new_structure2 = analyzer.SpacegroupAnalyzer(structure).get_symmetrized_structure()
    new_structure3 = analyzer.SpacegroupAnalyzer(structure).get_conventional_standard_structure()
    
    #a partir d 'ici je choisi de travailler sur la partie symmetrized car c'est la seule qui marche sur Jmol Cristal Symmetry Explorer
    
    #1 symmetry operations of the point group and space group
    
    SGclass2 = analyzer.SpacegroupAnalyzer(new_structure2) #symmetrized
        
    #print("point group operations  : ",SGclass2.get_point_group_operations(cartesian=False))
    PGO = SGclass2.get_point_group_operations(cartesian=False)
    
    

In [83]:
#2 get the 3 first atoms from the symmetrized structure
atomes = new_structure2.sites[0:3] 
position = np.array([atomes[0].coords,atomes[1].coords,atomes[2].coords])
#print(atomes)
#print('the position of the atoms:\n',position)


In [84]:
#3 get the rotation matrix for different symmetry operations 2, 7, 10
rot_m = np.array([PGO[2].rotation_matrix,PGO[7].rotation_matrix,PGO[10].rotation_matrix])
#print(rot_m)

In [85]:
#4 calculate the new positions of the atoms with the rotation matrix of each symmetry
new_positions = rot_m @ position.T

#each vector contains 3 matrixes / each matrix contains the new postion of the atom ( a colmun per atom)
#no need to take into account translator vector as it is null
#print(new_positions)


In [86]:
#5 make a nice print to summarize everything
print("space group symbol \n : ",SGclass2.get_space_group_operations())
print('\n')
print("base vectors : ")
print("length of the base vectors of the direct lattice (a,b,c): \n",new_structure2.lattice.abc)
print("angles (alpha,beta,gamma) of the base vectors of the direct lattice: \n",new_structure2.lattice.angles)
print('\n')
print("initial position of  the atoms :")

for i in range(len(position)) :
    print(atomes[i].specie)
    print( " initial position: " ,position[i])
print('\n')
print('#######################################################################################')
for j in range(len(rot_m)):
    print("Symmetry operation ",j+1)
    print("rotation matrix : \n")
    print(rot_m[j])
    print('\n')
    for k in range(len(position)):
        print("new position " + str(atomes[k].specie)+" : ")
        print(new_positions[j][:,k])
    print('\n')
    print('#######################################################################################')


space group symbol 
 :  R-3m (166) spacegroup


base vectors : 
length of the base vectors of the direct lattice (a,b,c): 
 (3.83664401, 6.612956506414123, 3.836643334933823)
angles (alpha,beta,gamma) of the base vectors of the direct lattice: 
 (106.86306102209353, 60.0000028878164, 106.86306313021774)


initial position of  the atoms :
La
 initial position:  [ 1.91832201 -1.10754373  3.11546884]
Ag
 initial position:  [0. 0. 0.]
O
 initial position:  [-1.82553395e-06  1.00775652e-06  2.07233155e+00]


#######################################################################################
Symmetry operation  1
rotation matrix : 

[[ 0.  0.  1.]
 [ 0.  1.  0.]
 [-1.  1. -1.]]


new position La : 
[ 3.11546884 -1.10754373 -6.14133458]
new position Ag : 
[0. 0. 0.]
new position O : 
[ 2.07233155e+00  1.00775652e-06 -2.07232872e+00]


#######################################################################################
Symmetry operation  2
rotation matrix : 

[[0. 0. 1.]
 [0. 1. 0.]
 [